version: '2'

services:
  kafka:
    image: wurstmeister/kafka:1.1.0
    depends_on:
      - zookeeper
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_BROKER_ID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: zookeeper:3.4

  #manager:
  #  image: sheepkiller/kafka-manager:alpine
  #  depends_on:
  #    - kafka
  #  ports:
  #    - "9000:9000"
  #  environment:
  #    ZK_HOSTS: zookeeper:2181

  # Default logging is user: admin, pass:admin
  #graylog:
  #  image: swcc/docker-graylog2
  #  ports:
  #    - "9001:9000"
  #    - "12201:12201"

  forwarder:
    image: screamingudder/forwarder:cc86f0a
    depends_on:
      - kafka
    network_mode: "host"
    volumes:
      - ./config-files/forwarder_config.json:/forwarder_config.json
    environment:
      CONFIG_FILE: "/forwarder_config.json"
      FAKE_PV_PERIOD_MS: "1000"

  event-producer:
    image: screamingudder/nexus-streamer:b9a5df7
    depends_on:
      - kafka
    network_mode: "host"
    environment:
      CONFIG_FILE: "/streamer_config.ini"
      KAFKA_BROKER: "localhost"
    volumes:
      - ./config-files/streamer_config.ini:/streamer_config.ini

  file-writer:
    image: screamingudder/file-writer:bc3acdf
    depends_on:
      - kafka
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config.json"
      KAFKA_BROKER: "localhost"
    volumes:
      - ./config-files/file_writer_config.json:/file_writer_config.json
      - ./output-files:/output-files
